services:
  postgres:
    image: postgres:16-alpine
    container_name: complaint_db
    environment:
      POSTGRES_USER: complaint_user
      POSTGRES_PASSWORD: complaint_pass
      POSTGRES_DB: complaints_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U complaint_user -d complaints_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
